name: Manual Test

on:
    workflow_dispatch:
        inputs:
            param1:
                description: 'Param 1'
                required: true
                default: 'param1'

jobs:
    Test-Jobs:
        runs-on:
            - ubuntu-latest
        steps:
            - name: Echo test
              run: |
                  echo ${{ github.event.inputs.param1 }}
                  uname -a
                  # ps -A
                  echo ${GITHUB_REF#refs/heads/}
                  echo ${GITHUB_REF}
                  git branch -a
                  git branch --show-current
                  git checkout ${GITHUB_REF}
                  git branch -a
                  git branch --show-current
